In [2]:
import numpy as np
from scipy.signal import convolve2d


filter = np.array([
    [1,1,1],
    [1,0,1],
    [1,1,1]
])

a = np.array([[1, 0, 1, 0, 1, 0, 1, 0],
              [0, 1, 0, 1, 0, 1, 0, 1],
              [1, 0, 1, 0, 1, 0, 1, 0],
              [0, 1, 0, 1, 0, 1, 0, 1],
              [1, 0, 1, 0, 1, 0, 1, 0],
              [0, 1, 0, 1, 0, 1, 0, 1]])

In [6]:
conv = convolve2d(a, filter, mode='same', boundary='fill', fillvalue=0)

In [8]:
print(conv)

[[1 3 2 3 2 3 2 2]
 [3 4 4 4 4 4 4 2]
 [2 4 4 4 4 4 4 3]
 [3 4 4 4 4 4 4 2]
 [2 4 4 4 4 4 4 3]
 [2 2 3 2 3 2 3 1]]
